### ISSUE TITLE
setupHiveTestTableDDL function , not returning Boolean

### ISSUE THREAD

**Issue by jonjuscorpion666** [CommBank/ebenezer#104]
As per the comments , setupHiveTestTableDDL returns true when table  created successfully and return false if not. But current implementation  returns  Hive[Unit ] and not boolean

**Comment by kfish** [comment]
Discussed this with @stephanh, the correct behaviour is to return in Unit as any Hive errors will throw an exception. Corrected documentation in 98b8285
