### ISSUE TITLE
dependency on commons-daemon breaks sbt compilation

### ISSUE THREAD

**Issue by jberthold** [CommBank/ebenezer#107]
I tried to add ebenezer to the dependencies of an sbt project
(in build.scala, adding 
` "au.com.cba.omnia"         %% "ebenezer"                      % "0.17.0-20150422010951-dd38ce5" `)
 
After adding this, sbt compile fails with an error about a "bad organisation"
```
artifactory: bad organisation found in http://..<internal-server>../commons-daemon/commons-daemon/1.0.3/commons-daemon-1.0.3.pom: expected='commons-daemon' found='org.apache.commons'
```
(this problem also happens with a public repo, btw)

I could work around this by filtering dependencies with `.exclude("commons-daemon", "commons-daemon")` , but I wonder how this can happen.

**Comment by SamRoberts** [comment]
If you check out `commons-daemon-1.0.3` in maven central, you can see that the pom is broken in that way. What I find hard to understand is why your software is looking at version `1.0.3` at all. That commit of ebenezer depends on uniform version `1.0.0-20150325230450-5af497f`, which depends on commons-daemon version `1.0.13`, which has the right organization. So I would be investigating what was pulling in version `1.0.3`.

**Comment by jberthold** [comment]
Certainly I will investigate this... the whole dependency story is a bit worrying (but then again, that might be a common thing, no matter which language and infrastructure is used).
I just wanted this problem to be documented somewhere, in case others run into it.

**Comment by jberthold** [comment]
I am closing this now. The root cause was a different package which forced commons-daemon back to this ancient version which has the problem described.
