### ISSUE TITLE
PartitionedHiveTable is planned to move to use `PartitionParquetScroogeSource`

### ISSUE THREAD

**Issue by rowandavies** [CommBank/ebenezer#125]
This will mean that we no longer use `PartitionHiveParquetScroogeSink`, nor depend on `cascading.hive` at all.

Instead we'll manage the hive meta-data via the `Hive` monad using `msck repair table` after writing the data.

This is motivated in part by an issue that occurs when Kerberos is enabled.  This change will be done starting next week - any concerns should be added here.

**Comment by vineethvarghese** [comment]
Addressed
