### ISSUE TITLE
Remove append partition hack from Hive parquet sources when moving to Execution completely

### ISSUE THREAD

**Issue by stephanh** [CommBank/ebenezer#70]
This hack doesn't work for the Execution stuff and we got a different approach in Maestro to work around it. We should remove this approach when we have moved away from the old API.

The approach in Maestro also fixes #43.

**Comment by rowandavies** [comment]
@stephanh What's the current status of this issue?

**Comment by vineethvarghese** [comment]
Not an issue now that there is no Hive parquet source
