### ISSUE TITLE
Add bracket method to Hive monad, as per Hdfs

### ISSUE THREAD

**Issue by SamRoberts** [CommBank/ebenezer#80]
The Hive monad should mirror the Hdfs monad. I attempted to add the bracket method to Hive, but when I execute the corresponding tests, they fail at runtime with a javac error: can't find the class `scala.Nothing$`.

**Comment by stephanh** [comment]
Do you have a branch with the code you tried?

**Comment by SamRoberts** [comment]
Sorry, no, I deleted it without thinking about preserving it. That's also why there is no detailed error message or code snipped in the issue ... :(

**Comment by SamRoberts** [comment]
But I copied the existing Hdfs code across with just enough modifications to make the tests sensible for the Hive monad.

**Comment by stephanh** [comment]
This was done as part of #85.
