### ISSUE TITLE
Delete deprecated HiveJob, etc.

### ISSUE THREAD

**Issue by stephanh** [CommBank/ebenezer#86]
Delete the deprecated HiveJob, etc.since it is superseded by the Hive monad.

**Comment by SamRoberts** [comment]
@stephanh what about `HiveExecution`?

**Comment by SamRoberts** [comment]
I was going to remove it as well, but it doesn't seem like the Hive monad gives you the ability to run large queries inside of a MR job

**Comment by SamRoberts** [comment]
And if that's the case, maybe we should remove the deprecated tags on `HiveExecution`?

**Comment by stephanh** [comment]
There is no difference between `Hive` and `HiveExecution` in how they run queries. They both just pass a query to hive and get it to run. Hive then converts that to an MR job.

**Comment by SamRoberts** [comment]
But the `HiveExecution` uses a tap which writes results to file as they appear and should handle large number of entries. All the `Hive` query methods try to convert the results into an in-memory list on the client. Surely there is a large difference there?

**Comment by stephanh** [comment]
Not that is an illusion. The taps are just used by Cascading to do its scheduling so that an output is first produced before it is used as an input. In the context of Execution where we do our own scheduling it's meaningless.

The only thing HiveExecution does with its output tap is ensure that the hive table is created as part of running the query. However, the query could be doing anything and there doesn't need to be any relationships between the query and the sink.

**Comment by SamRoberts** [comment]
Oh, duh, I should have remembered that. Will remove `HiveExecution`.

**Comment by stephanh** [comment]
@SamRoberts I assume this is done?

**Comment by SamRoberts** [comment]
Oh, yes, I must have accidentally removed the part of the commit message which would have made github automatically close this.
