### ISSUE TITLE
Parquet table format issue in CDH5.2

### ISSUE THREAD

**Issue by rakheshrnair** [CommBank/ebenezer#90]
The input/output formats and serde of hive tables created in CDH4.6  using Maestro was:
```
 ROW FORMAT SERDE\
  'parquet.hive.serde.ParquetHiveSerDe'\
STORED AS INPUTFORMAT\
  'parquet.hive.DeprecatedParquetInputFormat'\
OUTPUTFORMAT\
  'parquet.hive.DeprecatedParquetOutputFormat'\
```

But after the cluster upgrade to CDH5.2 all the existing table format changed to : 
```
ROW FORMAT SERDE\
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'\
STORED AS INPUTFORMAT\
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'\
OUTPUTFORMAT\
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat’\
```

So while running the maestro job to load data to some of the existing tables ,the  job is getting failed throwing the exception:

"Table already exist but schema doesn't match"

**Comment by stephanh** [comment]
So the second table format is the one produced by hive if you create a parquet table?

**Comment by stephanh** [comment]
We can update Maestro to match but we need to give some thought to transitioning all the tables created using the old DDL to the new DDL.

**Comment by rakheshrnair** [comment]
The second format is one in which hive is creating  the tables.
Also all the existing table format have been changed to the MapredParquetinputFormat after the upgrade.

**Comment by stephanh** [comment]
Ok.

We can release updated versions today or early tomorrow for CDH5 and CDH5V1 that use the right names but anything using viewHive or the Hive monad to create tables needs to be updated to the these versions before being deployed.

cc @snehalvidyan @sujeshce @anandsiva

**Comment by quintona** [comment]
What is the migration process for existing tables? Will the maestro job make the update or do we need to do a manual migration process?

**Comment by stephanh** [comment]
@quintona based on what @rakheshrnair said as part of the update all existing tables were modified to the use the new Serde.

So now we need to make sure that no loads get deployed that use the old version of ebenezer so no new tables get created with the old serde.

**Comment by stephanh** [comment]
@snehalvidyan @rakheshrnair @anandsiva @snehalvidyan do you have any thoughts on this? Are you ok to ensure that all loads are updated before going into production?

Is there anything else that needs to be handled?

**Comment by sujeshce** [comment]
Yes. We are yet to merge the changes to master. We can have one more change etl.util pointing to the new version. But not sure if we can do a full fledge testing. Will try to cover as much as possible in terms of testing. For deployment we can upgrade all projects pointing to the new one.

**Comment by rakheshrnair** [comment]
@stephanh I think we can close this issue. Thanks Stephan for the fix
